### ISSUE TITLE
The Account return type does not fully represent Margin accounts if a margin account is returned

### ISSUE THREAD

**Issue by jdgriffith** [MorpheusNephew/td-ameritrade#36]
https://github.com/MorpheusNephew/td-ameritrade/blob/4dae60c489f0246db94ecdd82022774f8d19f27d/src/clients/accounts-client.ts#L17

**Comment by jdgriffith** [comment]
This also applies to `getAccount`.

**Comment by MorpheusNephew** [comment]
Thanks for this, I noticed this as well. The issue is that the property `securitiesAccount` isn't of type `MarginAccount | CashAccount`
